USE PHOTO_PORTAL;
SELECT NAME FROM user 
WHERE (SELECT COUNT(*) FROM PHOTO_POST
WHERE CREATION_DATE >= CURDATE() 
AND CREATION_DATE < DATE_ADD(CURDATE(), INTERVAL 1 DAY)
AND USER_ID = USER.USER_ID) > 3;